name: Converting program to exe file
# Special thanks:
#  Elinsrc for help with actions
#  hype for new ideas for build app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        repository: GUTHUB_USERNAME/REPO_NAME # set your username and repo name

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pep8
        pip install pycodestyle
        pip install pywin32 pefile pyinstaller
        pip install -r requirements.txt
      continue-on-error: true

    - name: Checking file for PEP8
      run: pep8 PROGRAM_NAME.py # set your .py filename
      continue-on-error: true

    - name: Creating exe file for Windows
      run : pyinstaller --onefile PROGRAM_NAME.py # set your .py filename
      continue-on-error: true

    - name: Upload exe file to actions
      uses: actions/upload-artifact@v3
      with:
        name: NAME
        path: D:\a\REPO_NAME\REPO_NAME\dist\PROGRAM_NAME.exe # if error check your path in action debug
      continue-on-error: true
      if: ${{ always() }}