name: Converting my program to exe file with Nuitka

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        repository: ma3rd-nepon/autoPytoEXE

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.10'
          cache: 'pip'

    - name: Install Dependencies
      run: |
          pip install -r requirements.txt
      continue-on-error: true

    - name: Build Exe
      uses: Nuitka/Nuitka-Action@main
      with:
          nuitka-version: main
          script-name: PROGRAM_NAME.py
          onefile: true
          standalone: true # only exe/exe and cmd(program will use python)
          enable-plugins: pyqt5
          # include-module: module_name  if you have another modules
          windows-icon-from-ico: your_icon.ico # works only for windows
          disable-cache: true

      continue-on-error: true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }} Build
        path: |
          build/*.exe
          build/*.bin
          build/*.cmd/**/*
      continue-on-error: true
